---
  camera1:
    serial_no: "204100236"
    config: "no_config.json"
    stream: "true"
    framerate: "10"
    resize:
      apply: "false"
      res_x: "640"
      res_y: "480"

  camera2:
    serial_no: "213602316"
    config: "no_config.json"
    stream: "true"
    framerate: "10"
    resize:
      apply: "false"
      res_x: "640"
      res_y: "480"
